config/routes.rb
SDNPortal::Application.routes.draw do

  get "about/index"

  resources :forumposts

  resources :topics

  resources :categories

  resources :forums

  resources :projects

  resources :users

  resources :about
  resources :pages

  resources :comments

  resources :tags

  resources :newsposts

  resources :events
  
  resources :guests

  get "home/index"

  root :to => 'home#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :forumposts, :dependent => :destroy
	has_many :tags
	belongs_to :user
	belongs_to :category
	
	validates :title, :presence => true, :length => { :in => 2..50 }
	validates :user_id, :presence => true
	validates :category_id, :presence => true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter CASClient::Frameworks::Rails::Filter, :except => [ :show, :index ]
  before_filter :user_exists?, :except => [ :show, :index ]
  
  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])
	@topic.views = @topic.views.to_i + 1
	@topic.save
	@category = @topic.category
	@forum = @category.forum
	@forumposts =  @topic.forumposts.order(:created_at).paginate(:page => params[:page], :per_page => 6)
	@forumpost = Forumpost.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new
	@forumpost = Forumpost.new
	@category = params[:category] ? Category.find(params[:category]) : Category.first
	@forum = @category.forum

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
	@category = @topic.category
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])
	@topic.user = current_user
	
	respond_to do |format|
      if @topic.save
		@forumpost = Forumpost.new
		@forumpost.content = params[:forumpost][:content]
		@forumpost.user = current_user
		@forumpost.topic = @topic
		@forumpost.post_number = 1
		
		if @forumpost.save
			format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
			format.json { render json: @topic, status: :created, location: @topic }
		else
			@topic.destroy
			@topic.errors[:base] << "The first post must have content."
			format.html { render action: "new" }
			format.json { render json: @topic.errors, status: :unprocessable_entity }
		end
	  else
			format.html { render action: "new" }
			format.json { render json: @topic.errors, status: :unprocessable_entity }
	
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])
	if @topic.user == current_user || current_user.admin

		respond_to do |format|
		  if @topic.update_attributes(params[:topic])
			format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
			format.json { head :no_content }
		  else
			format.html { render action: "edit" }
			format.json { render json: @topic.errors, status: :unprocessable_entity }
		  end
		end
	
	else
		redirect_to @topic
	end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
	if @topic.user == current_user || current_user.admin
		@topic.destroy

		respond_to do |format|
		  format.html { redirect_to topics_url }
		  format.json { head :no_content }
		end
	
	else
		redirect_to @topic
	end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
	<%= f.label :category_id %><br />
	<% if @category %>
		<%= f.select(:category_id, Category.all.collect {|p| [ p.name, p.id ] }, :selected => @category.id) %>
	<% else %>
		<%= f.select(:category_id, Category.all.collect {|p| [ p.name, p.id ] }) %>
	<% end %>
  </div>
  
  <div class="fpost_field">
    <script type="text/javascript" src="/assets/tiny_mce/tiny_mce.js" ></script>
    <script type="text/javascript" >
    tinyMCE.init({
            mode : "textareas",
            theme : "advanced",
            plugins : "autolink, lists",

            theme_advanced_buttons1 : "bold,italic,|,bullist,numlist,|,link,unlink,image,code",
            theme_advanced_buttons2 : "",
            theme_advanced_buttons3 : "",
            theme_advanced_buttons4 : "",
            theme_advanced_toolbar_location : "bottom"
    });
    </script >
	<%= label(:forumpost, :content) %><br />
	<%= text_area(:forumpost, :content, :class => "fpost_field") %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/new.html.erb
<h1>New thread</h1>

<div class="forum_wrapper">
	<%= render 'form' %>
</div>
<%= forum_navigation_bar %>

app/views/topics/show.html.erb
<div class="forum_wrapper">

<h1><%= link_to @topic.title, @topic %> in <%= link_to @category.name, @category %></h1>

<div class="forum_extra_nav"><a href="#new_forumpost">Reply</a></div>
<div class="digg_pagination">
    <%= will_paginate @forumposts %>
</div>

	<div class="forum_spacer"></div>
		<div class="forum_spacer"></div>
		
	<% i = 1 %>
	<% @forumposts.each do |fpost| %>
		
		<div class="fpost_date">
			<span class="date_to_left"><%= fpost.created_at.strftime("%B %d %Y %I:%M %p") %> <% if fpost.created_at != fpost.updated_at %>
					Edited on: <%= fpost.updated_at.strftime("%B %d %Y %I:%M %p") %>
				<% end %>
			</span>
			<% if fpost.user == current_user || current_user.admin %>
				<%= link_to "Edit", edit_forumpost_path(fpost) %>
				<%= link_to "Delete", fpost, confirm: 'Are you sure?', method: :delete %>
			<% end %>
			<span class="fpost_number">#<%= fpost.post_number.to_s %></span>
		</div>

		<div class="fpost_content" style=<%= user_post_styles(fpost.user) %>>
			<%= safe_content(fpost.content).html_safe %>
			<br />---<br />
			<%= safer_content(fpost.user.signature).html_safe %>
		</div>

		<% if i.even? %>
			<div class="fpost_user_right">
				<div class="user_arrow" style=<%= user_post_styles(fpost.user) %>>

				</div>
				<div class="user_photo">
					<%= image_tag avatar_url(fpost.user) %>
				</div>
				<div class="fpost_user">
					<div class="fpost_username"><%= link_to fpost.user.username, fpost.user %></div>
					<!-- <div class="online_box"></div> Online -->
					<div class="fpost_member_since">Member since: <%= fpost.user.created_at.strftime("%B %d, %Y") %><br/>Posts: <%= fpost.user.forumposts.count %></div>
				</div>
			</div>
		<% else %>
			<div class="fpost_user_left">
				<div class="user_arrow" style=<%= user_post_styles(fpost.user) %>>
					
				</div>
				<div class="user_photo">
					<%= image_tag avatar_url(fpost.user) %>
				</div>
				<div class="fpost_user">
					<div class="fpost_username"><%= link_to fpost.user.username, fpost.user %></div>
					<!-- <div class="online_box"></div> Online -->
					<div class="fpost_member_since">Member since: <%= fpost.user.created_at.strftime("%B %d, %Y") %><br/>Posts: <%= fpost.user.forumposts.count %></div>
				</div>
			</div>
		<% end %>
		
		<div class="forum_spacer"></div>

		<% i = i + 1 %>
	<% end %>
	
<div class="digg_pagination">
    <%= will_paginate @forumposts, :container => false %>
</div>
<div class="forum_spacer"></div>

<%= form_for(@forumpost) do |f| %>
	<% if @forumpost.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@forumpost.errors.count, "error") %> prohibited this post from being saved:</h2>

			<ul>
			<% @forumpost.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="fpost_field">
	  <script type="text/javascript" src="/assets/tiny_mce/tiny_mce.js" ></script>
	  <script type="text/javascript" >
		tinyMCE.init({
		        mode : "textareas",
		        theme : "advanced",
		        plugins : "autolink, lists",

		        theme_advanced_buttons1 : "bold,italic,|,bullist,numlist,|,link,unlink,image,code",
		        theme_advanced_buttons2 : "",
		        theme_advanced_buttons3 : "",
		        theme_advanced_buttons4 : "",
		        theme_advanced_toolbar_location : "bottom"
		});
	  </script >
		<%= f.text_area :content, :class => "fpost_field" %>
	</div>
	<%= f.hidden_field(:topic_id, :value => @topic.id) %>
	<div class="actions">
		<%= f.submit "Reply" %>
	</div>
	<span id="new_forumpost"></span>
<% end %>

</div>
<%= forum_navigation_bar %>