config/routes.rb
SDNPortal::Application.routes.draw do

  get "about/index"

  resources :forumposts

  resources :topics

  resources :categories

  resources :forums

  resources :projects

  resources :users

  resources :about
  resources :pages

  resources :comments

  resources :tags

  resources :newsposts

  resources :events
  
  resources :guests

  get "home/index"

  root :to => 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tags
	has_many :users
	has_one :creator, :class_name => "User"
	
	validates :name, :presence => true, :length => { :in => 2..50 }
	validates :blurb, :length => { :in => 0..100 }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter CASClient::Frameworks::Rails::Filter, :except => [ :show, :index ]
  before_filter :user_exists?, :except => [ :show, :index ]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save

        @category = Category.create(:name => @project.name, :forum_id => Forum.find_by_name("Projects").id)

        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :blurb %><br />
    <%= f.text_field :blurb %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :class => "post_content_field" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Projects Index</h1>

<div class="projects_wrapper">

</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<div class="projects_wrapper">
	<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div class="projects_wrapper">
  <p>
    <b>Name:</b>
    <%= @project.name %>
  </p>

  <p>
    <b>Content:</b>
    <%= @project.content %>
  </p>

  <p>
    <b>Blurb:</b>
    <%= @project.blurb %>
  </p>

</div>