config/routes.rb
SDNPortal::Application.routes.draw do

  get "about/index"

  resources :forumposts

  resources :topics

  resources :categories

  resources :forums

  resources :projects

  resources :users

  resources :about
  resources :pages

  resources :comments

  resources :tags

  resources :newsposts

  resources :events
  
  resources :guests

  get "home/index"

  root :to => 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :topics, :dependent => :destroy
	belongs_to :forum
	
	validates :name, :presence => true
	validates :forum_id, :presence => true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter CASClient::Frameworks::Rails::Filter, :except => [ :show, :index ]
  before_filter :user_exists?, :except => [ :show, :index ]

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
	@forum = @category.forum
	@topics = @category.topics.paginate(:page => params[:page], :per_page => 20)
	#@threads = Topic.where(:category_id => @category.id).paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new
	@forum = Forum.find(params[:forum])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
	@forum = Forum.find(params[:forum])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new", :forum => params[:category][:forum] }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

	respond_to do |format|
	  if @category.update_attributes(params[:category])
		format.html { redirect_to @category, notice: 'Category was successfully updated.' }
		format.json { head :no_content }
	  else
		format.html { render action: "edit", :forum => params[:category][:forum] }
		format.json { render json: @category.errors, status: :unprocessable_entity }
	  end
	end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
	@forum = @category.forum
	if current_user.admin
		@category.destroy

		respond_to do |format|
		  format.html { redirect_to @forum }
		  format.json { head :no_content }
		end
	else
		redirect_to @category
	end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
	<%= f.label :forum_id %><br />
	<% if @forum %>
		<%= f.select(:forum_id, Forum.all.collect {|p| [ p.name, p.id ] }, :selected => @forum.id) %>
	<% else %>
		<%= f.select(:forum_id, Forum.all.collect {|p| [ p.name, p.id ] }) %>
	<% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing <%= @category.name %></h1>

<div class="forum_wrapper">
	<%= render 'form' %>
</div>
<%= forum_navigation_bar %>

app/views/categories/new.html.erb
<h1>New category</h1>

<div class="forum_wrapper">
	<%= render 'form' %>
</div>
<%= forum_navigation_bar %>

app/views/categories/show.html.erb
<div class="forum_wrapper">

<div class="forum_extra_nav"><%= link_to "New Thread", new_topic_path(:category => @category.id) %></div>

<div class="digg_pagination">
    <%= will_paginate @topics %>
</div>

	<table class="forum_table">
		<tr class="forum_def_row">
			<td><h4><%= link_to @category.name, @category %> in <%= link_to @forum.name, @forum %></h4><h5><%= @category.description %></h5></td>
			<td></td>
			<td></td>
		</tr>
		<tr class="forum_norm_row">
			<td>Thread</td>
			<td>Replies</td>
			<td>Views</td>
		</tr>
		
		<% @topics.each do |top| %>
			
			<tr class="forum_norm_row">
				<td><h4><%= link_to top.title, top %></h4><h5><%= link_to top.user.username, top.user %></h5></td>
				<td><%= top.forumposts.count.to_s %></td>
				<td><%= top.views.to_s %></td>
			</tr>
		
		<% end %>
		
	</table>
	
<div class="forum_extra_nav"><%= link_to "New Thread", new_topic_path(:category => @category.id) %></div>
<div class="digg_pagination">
    <%= will_paginate @topics, :container => false %>
</div>
<div class="forum_spacer"></div>

</div>
<%= forum_navigation_bar %>